version: '3.0'

services:
  web:
    container_name: chill-backend-web
    image: nginx:1-alpine
    volumes:
      - "./../:/data:rw"
      - "./../_logs/nginx:/data/logs:rw"
      - "./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:rw"
      - "./configs/nginx/conf.d/chill.conf:/etc/nginx/conf.d/chill.conf:rw"
    ports:
      - "10.227.64.1:85:85"
    networks:
      chill-backend:
        ipv4_address: 10.227.64.2
    depends_on:
      - fpm
  fpm:
    container_name: chill-backend-fpm
#    image: yiisoftware/yii2-php:7.4-fpm
    build:
      context: ./configs/php
    volumes:
      - "./../:/data:rw"
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini:rw"
    environment:
      - "DB_HOST=mysql"
      - "DB_DATABASE=chill"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "XDEBUG_CONFIG=remote_host=10.227.64.1 remote_enable=1 remote_autostart=0 remote_port=9008"
      - "PHP_IDE_CONFIG=serverName=chill-backend-fpm"
    networks:
      chill-backend:
        ipv4_address: 10.227.64.3
    depends_on:
      - mysql
  mysql:
    container_name: chill-backend-mysql
    image: mysql:5.7
#    build:
#      context: ./configs/mysql5.7
    volumes:
      - './../_logs/mysql:/var/lib/mysql:rw'
      - './configs/mysql5.7/my.cnf:/etc/mysql/my.cnf:rw'
      - './dump/chill.sql:/dump/chill.sql'
    environment:
      - MYSQL_ROOT_PASSWORD=123
    networks:
      chill-backend:
        ipv4_address: 10.227.64.4
  pma:
    container_name: chill-backend-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - VIRTUAL_HOST=pma.chill.local
      - PMA_HOST=mysql
    networks:
      chill-backend:
        ipv4_address: 10.227.64.6
    depends_on:
      - mysql
networks:
  chill-backend:
    ipam:
      driver: default
      config:
        - subnet: 10.227.64.0/24
    driver_opts:
      com.docker.network.bridge.name: chill-10